logging:
  level:
    liquibase: INFO
    root: INFO
    org.springframework.jdbc.core: TRACE
  file:
    name: logs/Schedule-app.log

spring:
  datasource:
    url: ${SPRING_DB_HOST}
    username: ${SPRING_DB_USER}
    password: ${SPRING_DB_USER}
  jpa:
    hibernate:
      ddl-auto: validate
    properties.hibernate:
      show_sql: false
      format_sql: false
    properties:
      hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  security:
    jwt:
      secret:
        access: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
        refresh: zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public
  task:
    scheduling:
      pool:
        size: 5

variables:
  auth-file-path: app/authFiles/auth.json
  openai-assistant: ${OPENAI-ASSISTANT}
  openai-token: ${OPENAI-TOKEN}
  telegram-token: ${TELEGRAM-TOKEN}

#Swagger
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#    display-request-duration: true